name: metatest
version: 0.2.0
author: Dart Team <misc@dartlang.org>
description: A package for testing Dart test frameworks.
homepage: https://github.com/dart-lang/metatest
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  test: '>=0.12.0 <0.13.0'
